is_official_build = true
is_component_build = false
win_vc = "C:/Program Files (x86)/Microsoft Visual Studio/18/BuildTools/VC"
win_toolchain_version = "14.50.35717"
win_sdk_version = "10.0.26100.0"
clang_win = "D:/python/getImageData/third_party/chrome153-clang"
clang_win_version = "24"
skia_enable_ganesh = true
skia_enable_graphite = true
skia_use_gl = true
skia_use_vulkan = false
skia_use_dawn = true
skia_use_direct3d = false
skia_use_angle = true
skia_gl_standard = "gles"
dawn_enable_d3d11 = true
dawn_enable_d3d12 = false
dawn_enable_opengles = false
dawn_enable_vulkan = false
skia_enable_pdf = false
skia_enable_skottie = false
skia_enable_tools = false
skia_use_expat = false
skia_use_libjpeg_turbo_decode = false
skia_use_libjpeg_turbo_encode = false
skia_use_libpng_decode = false
skia_use_libpng_encode = false
skia_use_libwebp_decode = false
skia_use_libwebp_encode = false
skia_use_wuffs = false
skia_use_icu = false
skia_use_bidi = true
skia_use_freetype = false
skia_enable_fontmgr_empty = true
skia_enable_fontmgr_win = true
skia_use_system_harfbuzz = false
skia_use_system_icu = false
skia_use_system_zlib = false
